export interface CommonPageHeaders {
    SRL: number,
    DES: string,
    PRIORITY: number,
    SYSTEM_SRL: number,
    ENDDOC: number,
    DOCUMENT_TYPES_SRL: string,
    VISIBLE: number,
    DETAILED_ACCOUNT_TITLE: string,
    DETAILED_ACCOUNT_SIDE_TITLE: string,
    BACK_DOC: number,
    DETAILED_GROUP_LIST: string,
    DETAILED_GROUP_SIDE_LIST: string,
    BANKDOC_NO_FLAG: number,
    REFRENCE_FLAG: number,
    DETAILED_ACCOUNT_LIST: string,
    DETAILED_ACCOUNT_SIDE_LIST: string,
    LOAN_FLAG: string,
    REFRENCE_DES: string,
    BANK_DATE_FLAG: string,
    CHECK_NO_FLAG: string,
    NATURE: string,
    BANK_NO_TITLE: string,
    BANK_DATE_TITLE: string
}
